### ISSUE TITLE
Dependency doesn't work

### ISSUE THREAD

**Issue by lucian303** [dgrnbrg/spyscope#16]
All I get when trying to use this is: RuntimeException No reader function for tag spy/t

Same for the other functions. I've listed this in my profiles.clj along with other packages, but it doesn't run. Adding it to the project doesn't work either.

**Comment by dgrnbrg** [comment]
Did you also make sure to list spyscope as an injected `require`?

Could you please share your `~/.lein/profiles.clj` and the `project.clj` you're using? I'd like to try to reproduce.

**Comment by lucian303** [comment]
Here's what I have:

```
{:user
	{:repl-options {:port 9119 :timeout 120000}
     :plugins []
     :dependencies [[spyscope "0.1.5"] [org.clojure/tools.trace "0.7.8"]]
     :injections [(require 'spyscope.core) (use 'clojure.tools.trace)]}}
```

**Comment by dgrnbrg** [comment]
Is that in your project.clj or profiles.clj? Could you post both, if you've
defined both?

**Comment by lucian303** [comment]
It's profiles.clj and working now! :)

**Comment by dgrnbrg** [comment]
Great! What was the solution? I'd like to document it for posterity to help
the next user who runs into this :-)

**Comment by lucian303** [comment]
I'm not really sure, but the code above in profiles.clj is working.
