### ISSUE TITLE
Release 0.1.6

### ISSUE THREAD

**Issue by holguinj** [dgrnbrg/spyscope#21]
PR #20 is necessary to use spyscope with Clojure 1.9 (alpha), but it isn't included with any released version. Would you mind cutting a release for those of us who want to experiment with the latest Clojure alphas but don't want to give up spyscope?

**Comment by dgrnbrg** [comment]
I would be happy to! Done!

https://clojars.org/spyscope

**Comment by holguinj** [comment]
Thanks!
